### ISSUE TITLE
Implement Concatenated Operation

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extension-geodetic-registry#27]
Fields:

- Aliases
- Accuracy
- Extent
- Scope
- Source CRS
- Target CRS
- Operation Version
- Coordinate Operations

**Comment by strogonoff** [comment]
@ribose-jeffreylau Do you remember where “source CRS” and “target CRS” fields come from? They don’t seem to be in 19111 (2019): 
<img width="1029" alt="Screenshot 2023-11-13 at 12 19 29" src="https://github.com/paneron/extension-geodetic-registry/assets/292959/8ca6c989-8c4d-4b8f-8935-af71b61a9716">

I’m not sure if I follow the logic of 19111 correctly, but I believe source and target CRS can be inferred from coordinate operations that comprise the concatenated operation in question.

**Comment by strogonoff** [comment]
Perhaps both CRS are meant as inferred read-only attributes…

**Comment by strogonoff** [comment]
We are not showing inferred source/target CRS yet, but we try to validate the chain:
<img width="1431" alt="Screenshot 2023-11-13 at 16 17 22" src="https://github.com/paneron/extension-geodetic-registry/assets/292959/b8a8676e-dfca-464b-8b91-898f73889c89">

It looks like our Conversions don’t have source not target CRS, not yet sure if it’s migration failure or it’s by design. Per standard it seems like conversions should have CRS like transformations.
