### ISSUE TITLE
Sheet processing: is transformation accuracy UoM standardized to always use registered UoM alias after the numeric value, or is it ad hoc/manual?

### ISSUE THREAD

**Issue by strogonoff** [paneron/extension-geodetic-registry#60]
In the register, we split accuracy by value and UoM. In the sheet, the value is provided as a single string like “0.001m”. We could resolve “m” as UoM alias and fail if not found/multiple matches.

**Comment by strogonoff** [comment]
There’s no unit in the sheet, meters are implied.

**Comment by strogonoff** [comment]
Can double-check the standard, and if other uoms are possible then leave the field, otherwise can just only leave value.

**Comment by ribose-jeffreylau** [comment]
@strogonoff Awaiting 2007 version of the standard.

**Comment by strogonoff** [comment]
I think we had the opportunity to check the standard by now?

**Comment by ribose-jeffreylau** [comment]
So from 19111:2007 Table 42 defining `CC_CoordinateOperation`, where the only occurrence of "accuracy"-related attribute is found, `Coordinate operation accuracy`, its data type is `DQ_Positional Accuracy`, with no other indicators of any particular unit of measure.  My take is that since it's positional, it has to be a unit for distance, hence using `m` for metres as the implicit unit is reasonable.
